### ISSUE TITLE
Imagick

### ISSUE THREAD

**Issue by KaraokeStu** [benyanke/docker-nextcloud#23]
Hi,

Could we get the ImageMgick PHP extension enabled please?

Maybe using the following in the dockerfile?

```
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libmagickwand-dev \
        libmagickcore-extra \
        && apt-get clean \
        && rm -rf /var/lib/apt/lists/*
RUN pecl install imagick
RUN docker-php-ext-enable imagick
```

**Comment by benyanke** [comment]
I'm not opposed to it. Feel free to open a PR with it, or I can do it later.

Out of curiosity, what feature does it provide to NextCloud?
