### ISSUE TITLE
ocm-provider path is not exposed as needed

### ISSUE THREAD

**Issue by kammerjaeger** [benyanke/docker-nextcloud#29]
Hi,
In my installation, nextcloud complains that /ocm-provider/ is not exposed correctly.
I changed the file: /rootfs/nginx/sites-enabled/nginx.conf in line 50 form
`...|ocs-provider/.+|...` to `...|oc[ms]-provider/.+|... and the same in line 63. Now it is working.
If you look at [nextcloud-in-the-webroot-of-nginx](https://docs.nextcloud.com/server/15/admin_manual/installation/nginx.html#nextcloud-in-the-webroot-of-nginx), there are other differences that may also be important.

Best,
David

**Comment by kammerjaeger** [comment]
Hi,
the second part is missing, could you also please change line 63? Without that it is not working.
Thanks,
David

**Comment by benyanke** [comment]
There you go - sorry about that, I didn't have an easy way to test, as my install is not showing these errors. In any case, try now after docker-hub rebuilds.

**Comment by kammerjaeger** [comment]
Thank you, it is working now.
