### ISSUE TITLE
Updating nextcloud without changes to container

### ISSUE THREAD

**Issue by sNiXx** [benyanke/docker-nextcloud#31]
First of all, thank you @benyanke for working on docker-nextcloud, I have been enjoying it for a few months now.

Now to my question:
In the past, I always updated my nextcloud instance by pulling the newest image and then updating the container.
However, I was wondering what the recommended upgrade route should be if, for whatever reason, we don't want to update the container? I've tried using the web based updater, which fails during the check for expected file ("The following extra files have been found: apps2"). Also, trying to go the manual route via updater.phar fails, because sudo seems to be missing from the container ("sudo: not found").

**Comment by benyanke** [comment]
Based on the docker workflow, where containers are designed to be immutable, upgrading in place isn't recommended or supported. Is there a specific reason you don't want to pull the latest image and remount your volumes? This is the typical docker methodology.

**Comment by sNiXx** [comment]
No specific reason, but thanks for clarifying! I guess I will continue to update according to the usual docker methodology. I'm closing this issue then, as my questions has been answered.

**Comment by benyanke** [comment]
Very good! Glad you were able to figure it out. Docker definitely encourages a different workflow, so always good to clarify.
