### ISSUE TITLE
NextCloud 17

### ISSUE THREAD

**Issue by unixfox** [benyanke/docker-nextcloud#35]
I'm opening an issue for NextCloud 17 to track the progress of the update to this new version. I'm doing this because my NextCloud instance just told me that I can upgrade to the new NextCloud 17 and it would be great if we could have this new version in the available images.

**Comment by benyanke** [comment]
I have tag `17` built for testing.

Can you give it a test and see?

**Comment by Steiniche** [comment]
Whats the status of this?

**Comment by benyanke** [comment]
I haven't had much of a chance to test yet - anyone here have any luck testing with the `17` tag?

**Comment by pulser** [comment]
The `17` tag works fine here - tested for a couple of weeks now.

**Comment by Stonemage** [comment]
Any chance we can get it updated to 17.0.1?

**Comment by benyanke** [comment]
bumped to 17.0.2 (f23f897a445252e97f5bad064b0f59c247e25ecf). Sorry for the delay on this all, I'll be hopefully spending some time this weekend to test and fully update this to 17.x.

**Comment by Steiniche** [comment]
Sounds great @benyanke appreciate that you are using some time on this.

**Comment by jmhbnz** [comment]
Hey just a note to say the `17` tag upgrade from `16` and subsequent general use is working great for me :)

**Comment by unixfox** [comment]
I finally tested the 17 tag and it's working fine from an upgrade of Nextcloud `16`.L

**Comment by benyanke** [comment]
very sorry for the delay on this. Had some urgent issues to attend to.

All is well, and 17 looks stable to me as well. Updating readme to note this.

**Comment by benyanke** [comment]
commit d26de4f43d15a7c498dac229aa8b8c633d6c2756 updates the repo to 17 (and notes the container image as stable).

**Comment by Steiniche** [comment]
Great @benyanke thanks for this!
