### ISSUE TITLE
Unable to pull benyanke/nextcloud:18

### ISSUE THREAD

**Issue by Stonemage** [benyanke/docker-nextcloud#37]
Hey Ben,
For some reason, I am unable to do the following:
docker pull benyanke/nextcloud:18

I also tried changing the 18 to 18.0 to no avail. Not sure what's going on with the tags, but they certainly aren't seeming to be working :|

**Comment by benyanke** [comment]
18 still isn’t working yet, so it’s 18-alpha. I tried it and it failed initially for me, and haven’t had further time to test and fix.

**Comment by unixfox** [comment]
Just tested 18 with the latest 18.0.1 by modifying the [Dockerfile.18.0](https://github.com/benyanke/docker-nextcloud/blob/master/Dockerfile.18.0) and it works great without any issue!
I created a PR for this new version: https://github.com/benyanke/docker-nextcloud/pull/39

**Comment by Stonemage** [comment]
Hey Ben,
Nextcloud has bumped up to 18.0.2 and 17.0.4 now, and it's been a while since we've seen an update. Any chance of an update and a small (does it install/run) test by chance? 😊

**Comment by Stonemage** [comment]
Has this become abandonware? No updates for 3 months and no responses to comments for weeks now...

**Comment by sNiXx** [comment]
Was wondering about that too, especially since Wonderfall is now up to date again... Would appreciate some quick feedback @benyanke

**Comment by benyanke** [comment]
Sorry for the delay...I simply haven't had much free time for FOSS stuff. Not trying to ghost you all! 

I've bumped to 17.0.5...My initial testing of 18 (here: https://hub.docker.com/r/benyanke/nextcloud/tags) didn't work, but I'd love to see if anyone is able to get that working!

**Comment by unixfox** [comment]
Actually I did and it works perfectly. I've my own fork of your image on quay since like a month: https://quay.io/repository/unixfox/docker-nextcloud

**Comment by sNiXx** [comment]
@benyanke: Could you merge @unixfox's PR #39 ? Changing the PHP version should be sufficient!

**Comment by benyanke** [comment]
The PR didn't work for me....more discussion in the PR.

**Comment by unixfox** [comment]
Why is there now a stale bot when the project didn't receive any update for 3 months?
